"""init schema

Revision ID: 4ece378b27b5
Revises: 
Create Date: 2026-08-16 18:43:06.250434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ece378b27b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED', name='gender'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_age_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'SHADOW_BANNED', name='user_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('user1_id', sa.Uuid(), nullable=False),
    sa.Column('user2_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='chat_room_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Enum('USER_LEFT', 'BOTH_LEFT', 'REPORTED', 'TIMEOUT', 'BANNED', name='end_reason'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_topic', sa.String(length=64), nullable=True),
    sa.Column('preferred_partner_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED', name='gender'), nullable=False),
    sa.Column('preferred_age_min', sa.Integer(), nullable=True),
    sa.Column('preferred_age_max', sa.Integer(), nullable=True),
    sa.Column('color_theme', sa.String(length=32), nullable=True),
    sa.Column('is_18_plus_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'EMOJI', 'SYSTEM', name='content_type'), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_table('search_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('filters_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('SEARCHING', 'MATCHED', 'CANCELLED', 'TIMEOUT', name='search_session_status'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_sessions')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_settings')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Ручная правка (не сгенерировано автоматически): Postgres ENUM-типы — это
    # отдельные объекты БД, не привязанные к одной таблице ('gender' используется
    # и в users, и в user_settings). autogenerate не удаляет их при дропе таблиц,
    # поэтому downgrade без этого блока не был полностью обратим upgrade —
    # повторный upgrade падал с "type already exists".
    bind = op.get_bind()
    postgresql.ENUM(name='search_session_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='content_type').drop(bind, checkfirst=True)
    postgresql.ENUM(name='end_reason').drop(bind, checkfirst=True)
    postgresql.ENUM(name='chat_room_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='user_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='gender').drop(bind, checkfirst=True)
